INSERT INTO INGREDIENTE (ID, NOME, PRECO) VALUES(1, 'Pão', 2.00);
INSERT INTO INGREDIENTE (ID, NOME, PRECO) VALUES(2, 'Batata palha', 0.40);
INSERT INTO INGREDIENTE (ID, NOME, PRECO) VALUES(3, 'Linguiça', 3.00);
INSERT INTO INGREDIENTE (ID, NOME, PRECO) VALUES(4, 'Salsicha', 2.00);
INSERT INTO INGREDIENTE (ID, NOME, PRECO) VALUES(5, 'Ovo de codorna', 0.30);
INSERT INTO INGREDIENTE (ID, NOME, PRECO) VALUES(6, 'Pure de batatas', 1.00);
INSERT INTO INGREDIENTE (ID, NOME, PRECO) VALUES(7, 'Milho', 0.20);


INSERT INTO LANCHE (ID, NOME) VALUES(8, 'Completo com Linguiça');
INSERT INTO LANCHE_INGREDIENTES (LANCHES_ID, INGREDIENTES_ID) VALUES (8, 1);
INSERT INTO LANCHE_INGREDIENTES (LANCHES_ID, INGREDIENTES_ID) VALUES (8, 2);
INSERT INTO LANCHE_INGREDIENTES (LANCHES_ID, INGREDIENTES_ID) VALUES (8, 3);
INSERT INTO LANCHE_INGREDIENTES (LANCHES_ID, INGREDIENTES_ID) VALUES (8, 5);
INSERT INTO LANCHE_INGREDIENTES (LANCHES_ID, INGREDIENTES_ID) VALUES (8, 6);
INSERT INTO LANCHE_INGREDIENTES (LANCHES_ID, INGREDIENTES_ID) VALUES (8, 7);

INSERT INTO LANCHE (ID, NOME) VALUES(9, 'Completo com Salsicha');
INSERT INTO LANCHE_INGREDIENTES (LANCHES_ID, INGREDIENTES_ID) VALUES (9, 1);
INSERT INTO LANCHE_INGREDIENTES (LANCHES_ID, INGREDIENTES_ID) VALUES (9, 2);
INSERT INTO LANCHE_INGREDIENTES (LANCHES_ID, INGREDIENTES_ID) VALUES (9, 4);
INSERT INTO LANCHE_INGREDIENTES (LANCHES_ID, INGREDIENTES_ID) VALUES (9, 5);
INSERT INTO LANCHE_INGREDIENTES (LANCHES_ID, INGREDIENTES_ID) VALUES (9, 6);
INSERT INTO LANCHE_INGREDIENTES (LANCHES_ID, INGREDIENTES_ID) VALUES (9, 7);


INSERT INTO LANCHE (ID, NOME) VALUES(10, 'Low carb completo');
INSERT INTO LANCHE_INGREDIENTES (LANCHES_ID, INGREDIENTES_ID) VALUES (10, 2);
INSERT INTO LANCHE_INGREDIENTES (LANCHES_ID, INGREDIENTES_ID) VALUES (10, 3);
INSERT INTO LANCHE_INGREDIENTES (LANCHES_ID, INGREDIENTES_ID) VALUES (10, 4);
INSERT INTO LANCHE_INGREDIENTES (LANCHES_ID, INGREDIENTES_ID) VALUES (10, 5);
INSERT INTO LANCHE_INGREDIENTES (LANCHES_ID, INGREDIENTES_ID) VALUES (10, 6);
INSERT INTO LANCHE_INGREDIENTES (LANCHES_ID, INGREDIENTES_ID) VALUES (10, 7);


INSERT INTO PROMOCAO (ID, NOME, BASE_CALCULO, TIPO_CALCULO) VALUES(11, 'Completo (Linguiça) + refrigerante 300ml', 3.00, 1);
INSERT INTO ITEM_PROMOCAO (ID, LANCHE_ID, QUANTIDADE) VALUES(12, 8, 1);
INSERT INTO PROMOCAO_ITENS (PROMOCOES_ID, ITENS_ID) VALUES(11, 12);

INSERT INTO PROMOCAO (ID, NOME, BASE_CALCULO, TIPO_CALCULO) VALUES(13, 'Completo (Salsicha) + refrigerante 300ml', 3.00, 1);
INSERT INTO ITEM_PROMOCAO (ID, LANCHE_ID, QUANTIDADE) VALUES(14, 9, 1);
INSERT INTO PROMOCAO_ITENS (PROMOCOES_ID, ITENS_ID) VALUES(13, 14);



INSERT INTO PROMOCAO (ID, NOME, BASE_CALCULO, TIPO_CALCULO) VALUES(15, 'Completo (Linguiça) + cerveja longneck', 6.00, 1);
INSERT INTO ITEM_PROMOCAO (ID, LANCHE_ID, QUANTIDADE) VALUES(16, 8, 1);
INSERT INTO PROMOCAO_ITENS (PROMOCOES_ID, ITENS_ID) VALUES(15, 16);

INSERT INTO PROMOCAO (ID, NOME, BASE_CALCULO, TIPO_CALCULO) VALUES(17, 'Completo (Salsicha) + cerveja longneck', 6.00, 1);
INSERT INTO ITEM_PROMOCAO (ID, LANCHE_ID, QUANTIDADE) VALUES(18, 8, 1);
INSERT INTO PROMOCAO_ITENS (PROMOCOES_ID, ITENS_ID) VALUES(17, 18);



INSERT INTO PROMOCAO (ID, NOME, BASE_CALCULO, TIPO_CALCULO) VALUES(19, '2 Completos (Linguiça)', 10, 4);
INSERT INTO ITEM_PROMOCAO (ID, LANCHE_ID, QUANTIDADE) VALUES(20, 8, 2);
INSERT INTO PROMOCAO_ITENS (PROMOCOES_ID, ITENS_ID) VALUES(19, 20);

INSERT INTO PROMOCAO (ID, NOME, BASE_CALCULO, TIPO_CALCULO) VALUES(21, '2 Completos (Salsicha)', 10, 4);
INSERT INTO ITEM_PROMOCAO (ID, LANCHE_ID, QUANTIDADE) VALUES(22, 9, 2);
INSERT INTO PROMOCAO_ITENS (PROMOCOES_ID, ITENS_ID) VALUES(21, 22);